update

diff --git a/confirm b/confirm
--- a/confirm
+++ b/confirm
@@ -1,5 +1,4 @@
-# -*- coding: utf-8 -*-
-#
+#!/usr/bin/env bash
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
 # distributed with this work for additional information
@@ -16,31 +15,37 @@
 # KIND, either express or implied.  See the License for the
 # specific language governing permissions and limitations
 # under the License.
-"""
-This dag only runs some simple tasks to test Airflow's task execution.
-"""
-from datetime import datetime, timedelta
+set -euo pipefail
 
-from airflow import DAG
-from airflow import utils
-from airflow.operators.dummy_operator import DummyOperator
+if [[ "${FORCE_ANSWER_TO_QUESTIONS:=""}" != "" ]]; then
+    RESPONSE=${FORCE_ANSWER_TO_QUESTIONS}
+    echo
+    echo "Forcing response '${FORCE_ANSWER_TO_QUESTIONS}' to ${1}."
+    case "${RESPONSE}" in
+        [yY][eE][sS]|[yY])
+            exit 0 ;;
+        [qQ][uU][iI][tT]|[qQ])
+            exit 2 ;;
+        *)
+            exit 1 ;;
+    esac
+else
+    echo
+    echo "Please confirm ${1} images. Are you sure? [y/N/q]"
+    read -r RESPONSE
+fi
 
-now = datetime.now()
-now_to_the_hour = (
-    now - timedelta(0, 0, 0, 0, 0, 3)
-).replace(minute=0, second=0, microsecond=0)
-START_DATE = now_to_the_hour
-DAG_NAME = 'test_dag_v1'
-
-default_args = {
-    'owner': 'airflow',
-    'depends_on_past': True,
-    'start_date': utils.dates.days_ago(2)
-}
-dag = DAG(DAG_NAME, schedule_interval='*/10 * * * *', default_args=default_args)
-
-run_this_1 = DummyOperator(task_id='run_this_1', dag=dag)
-run_this_2 = DummyOperator(task_id='run_this_2', dag=dag)
-run_this_2.set_upstream(run_this_1)
-run_this_3 = DummyOperator(task_id='run_this_3', dag=dag)
-run_this_3.set_upstream(run_this_2)
+case "${RESPONSE}" in
+    [yY][eE][sS]|[yY])
+        echo "The answer is 'yes'. Attempting to ${1} images. This can take some time !"
+        exit 0
+        ;;
+    [qQ][uU][iI][tT]|[qQ])
+        echo "The answer is 'quit'. Quitting now!"
+        exit 2
+        ;;
+    *)
+        echo "The answer is 'no'. Skipping attempt to ${1} images."
+        exit 1
+        ;;
+esac
